print("Abrindo a página de: Login")
print("Teste da funcionalidade de Login Iniciado..")
print("Inserindo números (171717) no campo RA/Matrícula")
print("Inserindo números (1234) no campo Senha")
print("Página de resposta sem erros!")
print("Inserindo letras (Usuario) no campo RA/Matrícula")
print("Inserindo números (1234) no campo Senha")
print("Página de resposta sem erros!")
print("Inserindo caracteres especiais (@!@#%) no campo RA/Matrícula")
print("Inserindo números (1234) no campo Senha")
print("Página de resposta sem erros!")
print("Inserindo letras (Usuario) no campo RA/Matrícula")
print("Inserindo letras (Senha) no campo Senha")
print("Página de resposta sem erros!")
print("Inserindo caracteres especiais (@!@#%) no campo RA/Matrícula")
print("Inserindo letras (Senha) no campo Senha")
print("Página de resposta sem erros!")
print("Teste Aprovado!")