# Generated by Django 2.1.5 on 2019-10-05 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gerenciador.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2019, 10, 5, 18, 38, 26, 543401), help_text='Data da Defesa')),
                ('hora', models.TimeField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False, help_text='Aprovação')),
                ('entrega', models.FileField(blank=True, null=True, upload_to='')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Observações da Defesa', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', help_text='Título da Atividade', max_length=150)),
                ('data_inicio', models.DateField(help_text='Data de início da atividade')),
                ('data_final', models.DateField(help_text='Data final da entrega da Atividade')),
                ('arquivo', models.BooleanField(default=False, help_text='Atividade terá entrega')),
                ('aprovado', models.BooleanField(default=False, help_text='Aprovação')),
                ('entrega', models.FileField(blank=True, null=True, upload_to='', validators=[gerenciador.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', help_text='Título do Trabalho', max_length=150)),
                ('descricao', models.CharField(default='', help_text='Descrição do Trabalho', max_length=30000)),
                ('tipo', models.CharField(choices=[('Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Concluido', 'Concluido')], default='Andamento', max_length=30)),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data de Início')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(default='', max_length=1500)),
                ('email', models.EmailField(default='', max_length=500)),
                ('password', models.CharField(default='', max_length=150)),
                ('ra', models.PositiveIntegerField(default='', primary_key=True, serialize=False)),
                ('perfil', models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Coordenador', 'Coordenador')], default='Aluno', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trabalho',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aluno', to='gerenciador.Usuario'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Professor', to='gerenciador.Usuario'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trabalho', to='gerenciador.Trabalho'),
        ),
        migrations.AddField(
            model_name='ata',
            name='avaliadores',
            field=models.ManyToManyField(related_name='Avaliador', to='gerenciador.Usuario'),
        ),
        migrations.AddField(
            model_name='ata',
            name='monografia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Atividade'),
        ),
        migrations.AddField(
            model_name='ata',
            name='tcc',
            field=models.ForeignKey(blank=True, help_text='TCC em Andamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TCC', to='gerenciador.Trabalho'),
        ),
    ]
