# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Coordenador', 'Coordenador')], default='Aluno', max_length=20),
        ),
    ]
