# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
