# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_auto_20181206_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
