# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-08 01:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_remove_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
