# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-08 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_auto_20181207_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
        ),
    ]
