# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_auto_20181207_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', help_text='Descri\xe7\xe3o do Trabalho', max_length=150)),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data de In\xedcio')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to='gerenciador.Usuario')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='gerenciador.Usuario')),
            ],
        ),
    ]
