# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='tipo',
            field=models.CharField(choices=[('Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Concluido', 'Concluido')], default='Andamento', max_length=30),
        ),
    ]
