# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-01 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0009_auto_20190101_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to='gerenciador.Usuario'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='gerenciador.Usuario'),
        ),
    ]
