# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0011_auto_20190101_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', help_text='T\xedtulo da Atividade', max_length=150)),
                ('data_inicio', models.DateField(help_text='Data de in\xedcio da atividade')),
                ('data_final', models.DateField(help_text='Data final da entrega da Atividade')),
                ('entrega', models.FileField(upload_to='entregas/')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trabalho', to='gerenciador.Trabalho')),
            ],
        ),
    ]
